version: "3.9"

networks:
  mcp_net:                # ← 固定名字
    name: mcp_net

services:
  consul:
    image: hashicorp/consul:1.19.0
    container_name: consul
    restart: always
    command: >
      agent
      -server
      -bootstrap-expect=1
      -ui
      -node=consul-1
      -datacenter=dc1
      -client=0.0.0.0
      -bind=0.0.0.0
      -data-dir=/consul/data
    ports:
      - "8500:8500"   # Web UI / HTTP API
      - "8600:8600/udp" # DNS
      - "8600:8600/tcp"
#    environment:
#      CONSUL_BIND_INTERFACE: eth0
    volumes:
      - ./data/consul/data:/consul/data
    networks:
      mcp_net: # ← 固定名字
